### PR TITLE
Tracks number of clicks to Maker Party page on Teach Site

### LINKED ISSUE #144: Add analytics to Maker Party promo
We have a new promotional component on https://beta.webmaker.org/. Significant traffic will arrive soon. Do we have event tracking in place for this campaign? 

@mmmavis @adamlofting @hannahkane @secretrobotron

### PR DESCRIPTION
**Pull request by mmmavis**
This fixes #144

### CODE REVIEW

**Comment by errietta** [comment]
R+

**Comment by mmmavis** [comment]
thank you @errietta :wink:

**Comment by mmmavis** [comment]
@k88hudson not sure how the release schedule is like for this repo but we are hoping to get this out before Maker Party starts(tomorrow). Do you think it's possible to push this live today?

**Comment by k88hudson** [comment]
@mmmavis that should be doable, i'll push to staging to make sure there aren't any issues

**Comment by mmmavis** [comment]
hey @k88hudson what's the url to staging - just wanna verify things are good there.  And what will the next step be if staging looks fine?

**Comment by k88hudson** [comment]
@mmmavis staging here: https://webmaker-desktop-staging.herokuapp.com/#/

We;re about to push prod

**Comment by k88hudson** [comment]
Ok, should be deployed any second now!

**Comment by mmmavis** [comment]
yayyy thank you @k88hudson!

**Pull request merged**
