### PR TITLE
Remove old project review, replace with player

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by k88hudson** [comment]
@thisandagain R?

**Comment by ryanwarsaw** [comment]
@k88hudson The Travis CI build appears to have failed.

**Comment by k88hudson** [comment]
@Pomax R?

**Comment by gvn** [comment]
Can we fix the file names now so that both core and browser use `project.jsx`?

I used `player.jsx` because I thought `project` was already in use, but it's confusing having two names for the same thing.

**Comment by gvn** [comment]
This would probably impact sharing links, so bear that in mind...

**Comment by k88hudson** [comment]
@gvn i think it's better to stick with the old URL scheme to avoid changes/compatibility issues with versions of the android app that have already been released, but i renamed the files, good call

**Comment by k88hudson** [comment]
@gvn lol actually the old url scheme is /project anyway :P haha

**Comment by gvn** [comment]
Hah that works out then!

Also, this comment will need updating: https://github.com/mozilla/webmaker-core/blob/develop/src/pages/project/project.jsx#L3

**Comment by gvn** [comment]
Much better. Glad we have that cleaned up. R+!

Can you just do this tweak: https://github.com/mozilla/webmaker-browser/pull/204#issuecomment-125695533 as a follow up?

**Comment by k88hudson** [comment]
@gvn will do

**Pull request merged**
