### PR TITLE
Player header

### PR DESCRIPTION
**Pull request by gvn**
Adding the header for the browser based player

### CODE REVIEW

**Comment by gvn** [comment]
Test URL: http://localhost:8000/#/player?user=1&project=1

**Comment by gvn** [comment]
Related to: #154

**Comment by k88hudson** [comment]
I'm getting a 404 for `newlogo.png`

**Comment by k88hudson** [comment]
longer text is squishing the logo's container element, can you throw a `flex-shrink: 0` on it?

**Comment by k88hudson** [comment]
R+

**Pull request merged**
