### PR TITLE
[#62] Redirect Android devices to playstore

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by thisandagain** [comment]
Is this meant to address https://github.com/mozilla/webmaker-desktop/issues/62 ?

**Comment by k88hudson** [comment]
@thisandagain yes

**Comment by thisandagain** [comment]
Cool. So the approach is great, but a couple things:
- This should apply to sharing links rather than the `splash.jsx`
- The logic should be to redirect user to play store if _not_ on Android

**Comment by xmatthewx** [comment]
@thisandagain - if an android user doesn't have the app, why not send them to the play store?

**Comment by k88hudson** [comment]
Replaced this with https://github.com/mozilla/webmaker-desktop/pull/136

**Pull request closed without merging**
