### PR TITLE
lock webmaker core to a commit for now

### PR DESCRIPTION
**Pull request by k88hudson**
Interim solution until we start tagging things

### CODE REVIEW

**Comment by gvn** [comment]
Sorry...I missed this earlier. Locking should be fine, but we may want to bump the hash before landing.

**Comment by thisandagain** [comment]
@gvn @k88hudson Did you folks still want to land this?

**Comment by gvn** [comment]
Working fine locally, but failing Travis for some reason...

**Comment by k88hudson** [comment]
@gvn looked like it was a random travis failure. hurray

**Pull request merged**
