### PR TITLE
Adding Tools link to footer. 

### PR DESCRIPTION
**Pull request by vazquez**
Fixes https://github.com/mozilla/webmaker-core/issues/303

### CODE REVIEW

**Comment by mmmavis** [comment]
lovely! :heart_eyes: 

one thing - we might want to consider wrapping text for small devices
screen shot 2015-07-16 at 13 22 29

**Comment by xmatthewx** [comment]
Agreed. Tools should be centered on it's own line before any other items wrap.

**Comment by vazquez** [comment]
Great catch @mmmavis. Fix is up :)

**Comment by mmmavis** [comment]
screen shot 2015-07-17 at 11 12 10
:heart_eyes: :+1: thanks @vazquez

**Pull request merged**
