### PR TITLE
Adding Thimble Promo

### PR DESCRIPTION
**Pull request by vazquez**

### CODE REVIEW

**Comment by vazquez** [comment]
@mmmavis Can I get a PR review on this please? 😄

**Comment by xmatthewx** [comment]
yay!

**Comment by mmmavis** [comment]
Looks great! R+ :tada: 

Wondering if we should remove Maker Party related strings from `en-US.yaml` and `#mp-promo` CSS code? Feel like it's unlikely that we will reuse them again... but I might be wrong :wink:

**Comment by vazquez** [comment]
I think we might use them again based on our convo with Erika today. I'll reach out to Paul before removing that code!

**Comment by mmmavis** [comment]
sounds good! thanks @vazquez :dancer:

**Pull request merged**
